import Header from "@/components/header";
import Footer from "@/components/footer";

import './globals.css'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-Background py-[32px] px-[90px]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
